### PR TITLE
removed height property from the lightbox, fixed #495

### LINKED ISSUE #495: Lightbox white background issue
screen shot 2017-05-11 at 16 53 21
Too much white on the lightbox

### PR DESCRIPTION
**Pull request by tomoversluizen**

### CODE REVIEW

**Comment by IanCStewart** [comment]
What happens when an image is to high? And or to low? Could you add a screenshot of these scenarios

**Comment by tomoversluizen** [comment]
**Dit is met `height: 80%;`**
screen shot 2017-05-11 at 17 17 13
screen shot 2017-05-11 at 17 17 58

**Dit is zonder `height: 80%`**
screen shot 2017-05-11 at 17 17 26
screen shot 2017-05-11 at 17 18 07

**Comment by IanCStewart** [comment]
I meant higher then the height of the screen ;)

**Comment by tomoversluizen** [comment]
screen shot 2017-05-12 at 09 00 02
This happens when the image is too big for the screen

**Comment by IanCStewart** [comment]
That doesn't look like wanted behaviour. If the image is higher than 100% we want it to scale down.

**Comment by sjaakluthart** [comment]
I'd say `maxHeight: 80%` should do the trick

**Comment by tomoversluizen** [comment]
screen shot 2017-05-12 at 12 02 34
this is what happens when you do `maxHeight: 80%` with a large image. Maybe it has something to do with other elements that are blocking eachother?

**Comment by sjaakluthart** [comment]
@tomoversluizen try adding `height: 100%` and `width: auto` to the image inside the box

**Comment by sjaakluthart** [comment]
Just removing `height: 80` doesn't seem right... please fix it

**Pull request closed without merging**
