### PR TITLE
[WIP] Component tests

### PR DESCRIPTION
**Pull request by IanCStewart**

### CODE REVIEW

**Comment by larstadema** [comment]
Also, you define a wrapper in beforeEach, but in the last test you use the component separately again. So either define it in beforeEach and use it everywhere, or shallow mount it in every test.

**Comment by sjaakluthart** [comment]
@larstadema I'm not sure if wrapping the component with HOC's could or should be called a 'container'. It's different from react-redux' connect.

**Comment by IanCStewart** [comment]
I think i agree with @sjaakluthart on the container part. This is not react/redux this is just plain react. For the beforeEach wrapper part the last one spies on the styles not sure if it will work if i dount shallow mount it after initiating the spy.

**Comment by larstadema** [comment]
Agreed, but it does look weird compared to our client, index.js there is just a import/export and that's it. 

As for the beforeEach, I think you should just mount the component inside the tests. This is what the enzyme docs also do. Idea behind it is the control of prop you. 

It makes testing different props easier:

```
const combinedProps = {
  ...props,
  customProp: 'henk'
}
const wrapper = shallow(<MyComponent props={combinedProps} />);
```

**Pull request merged**
